name: "Run tests"

on:

  push:
    branch: [ add_CI_tests ]
  
  workflow_dispatch:
  
 jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: slicer wrapper test on cpu  # run .py script
        run: |
          python petals_locsl_parallel/slicer_wrapper_test_cpu.py
          
